/* ==========================================================================
   Oblasť: ČAROVNÁ PRÍRODA
   ========================================================================== */
addLessons('nat', [
  /* ------------------------------------------------------------------ */
  {
    id: 'nat-babies', title: 'Mamy a mláďatá', sub: 'ako sa volá mláďa?', icon: '🐣',
    badge: { e: '🐣', name: 'Mamička mláďatiek', desc: 'Vieš, ako sa volajú mláďatá' },
    items: [
      { n: 'krava', gen: 'kravy', p: 'foto:mama-krava', b: 'teľa', f: 'Mláďa kravy je teľa. Krava nám dáva mlieko.' },
      { n: 'sliepka', gen: 'sliepky', p: 'foto:mama-sliepka', b: 'kuriatko', f: 'Z vajíčka sa vyliahne kuriatko. Otec kuriatok je kohút.' },
      { n: 'ovca', gen: 'ovce', p: 'foto:mama-ovca', b: 'jahňa', f: 'Mláďa ovce je jahňa. Z ovčej vlny sa pletú svetre.' },
      { n: 'koza', gen: 'kozy', p: 'foto:mama-koza', b: 'kozliatko', f: 'Mláďa kozy je kozliatko. Rado skáče po skalách.' },
      { n: 'kôň', gen: 'koňa', p: 'foto:mama-kon', b: 'žriebä', f: 'Mláďa koňa je žriebä. Mama je kobyla.' },
      { n: 'prasa', gen: 'prasaťa', p: 'foto:mama-prasa', b: 'prasiatko', f: 'Mláďa prasaťa je prasiatko. Rado sa váľa v blate.' },
      { n: 'pes', gen: 'psa', p: 'foto:mama-pes', b: 'šteňa', f: 'Mláďa psa je šteňa.' },
      { n: 'mačka', gen: 'mačky', p: 'foto:mama-macka', b: 'mačiatko', f: 'Mláďa mačky je mačiatko. Po narodení je slepé.' },
      { n: 'kačica', gen: 'kačice', p: 'foto:mama-kacica', b: 'káčatko', f: 'Mláďa kačice je káčatko. Už malé vie plávať.' },
      { n: 'medvedica', gen: 'medvedice', p: 'foto:mama-medvedica', b: 'medvieďa', f: 'Mláďa medveďa je medvieďa. Rodí sa v zime v brlohu.' },
      { n: 'líška', gen: 'líšky', p: 'foto:mama-liska', b: 'líšťa', f: 'Mláďa líšky je líšťa. Líška býva v nore.' },
      { n: 'žaba', gen: 'žaby', p: 'foto:zaba', b: 'žubrienka', f: 'Mláďa žaby je žubrienka. Žije vo vode a má chvost ako rybka.' },
    ],
    quiz: [
      { q: 'Kto je otec kuriatok?', a: 'kohút', o: ['býk', 'baran', 'kocúr'] },
      { q: 'Ako sa volá otec teliatka?', a: 'býk', o: ['kohút', 'baran', 'žrebec'] },
      { q: 'Ako sa volá otec jahniatka?', a: 'baran', o: ['kozol', 'býk', 'kanec'] },
      { q: 'Ktoré mláďa sa liahne z vajíčka?', a: 'kuriatko', o: ['šteňa', 'teľa', 'žriebä'] },
      { q: 'Kde spí medvedica s medvieďatami v zime?', a: 'v brlohu', o: ['v hniezde', 'v úli', 'v maštali'] },
      { q: 'Čo pije malé teliatko?', a: 'mlieko', o: ['čaj', 'limonádu', 'kávu'] },
      { q: 'Kde býva kôň?', a: 'v stajni', o: ['v úli', 'v nore', 'v hniezde'] },
    ],
    tf: [
      { s: 'Mláďa kravy je teľa.', ok: true },
      { s: 'Mláďa ovce je kuriatko.', ok: false, f: 'Mláďa ovce je jahňa. Kuriatko je mláďa sliepky.' },
      { s: 'Mláďa koňa je žriebä.', ok: true },
      { s: 'Mláďa psa je mačiatko.', ok: false, f: 'Mláďa psa je šteňa.' },
      { s: 'Žubrienka žije vo vode.', ok: true },
      { s: 'Mláďa líšky je líšťa.', ok: true },
      { s: 'Kuriatka sa rodia v brlohu.', ok: false, f: 'Kuriatka sa liahnu z vajíčok.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'name', rounds: 6, opts: 3, ans: 'b', ask: 'Ako sa volá mláďa {gen}?', title: 'Mláďatko' },
      { type: 'match', pairs: 5, a: 'p', b: 'b', title: 'Priraď mláďa' },
      { type: 'memory', pairs: 5, a: 'p', b: 'b' },
      { type: 'quiz', rounds: 5 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-homes', title: 'Kto kde býva?', sub: 'les, dvor, voda, prales, púšť', icon: '🏡',
    badge: { e: '🦉', name: 'Strážkyňa lesa', desc: 'Vieš, kde zvieratká bývajú' },
    items: [
      { n: 'les', p: 'foto:les', f: 'V lese žijú jelene, srny, líšky, veveričky, diviaky a sovy.' },
      { n: 'dvor', p: 'foto:dvor', f: 'Na dvore a na farme chovajú ľudia kravy, sliepky, prasiatka a kone.' },
      { n: 'voda', p: 'foto:voda', f: 'V mori a v rybníkoch žijú ryby, kraby, chobotnice aj delfíny.' },
      { n: 'prales', p: 'foto:prales', f: 'V teplom pralese žijú opice, papagáje, tigre a leňochody.' },
      { n: 'púšť', p: 'foto:pust', f: 'Na púšti je horúco a sucho. Žijú tu ťavy, škorpióny a jašterice.' },
      { n: 'nora', p: 'foto:nora', f: 'Niektoré zvieratá si robia domček pod zemou – noru. Napríklad líška alebo jazvec.' },
      { n: 'hniezdo', p: 'foto:hniezdo', f: 'Vtáky si stavajú hniezda z vetvičiek a v nich sedia na vajíčkach.' },
      { n: 'úľ', p: 'foto:ul', f: 'Včely bývajú v úli a vyrábajú v ňom med.' },
    ],
    sort: {
      title: 'Kde žije?',
      bins: [
        { id: 'les', n: 'les', p: 'foto:les' },
        { id: 'dvor', n: 'dvor', p: 'foto:dvor' },
        { id: 'voda', n: 'voda', p: 'foto:voda' },
        { id: 'prales', n: 'prales', p: 'foto:prales' },
        { id: 'pust', n: 'púšť', p: 'foto:pust' },
      ],
      items: [
        { n: 'jeleň', p: 'foto:jelen', b: 'les' }, { n: 'veverička', p: 'foto:veverica', b: 'les' }, { n: 'diviak', p: 'foto:diviak', b: 'les' },
        { n: 'sova', p: 'foto:sova', b: 'les' }, { n: 'ježko', p: 'foto:jezko', b: 'les' },
        { n: 'krava', p: 'foto:krava', b: 'dvor' }, { n: 'sliepka', p: 'foto:sliepka', b: 'dvor' }, { n: 'prasiatko', p: 'foto:prasiatko', b: 'dvor' }, { n: 'ovca', p: 'foto:ovca', b: 'dvor' },
        { n: 'ryba', p: 'foto:ryba', b: 'voda' }, { n: 'chobotnica', p: 'foto:chobotnica', b: 'voda' }, { n: 'krab', p: 'foto:krab', b: 'voda' }, { n: 'delfín', p: 'foto:delfin', b: 'voda' },
        { n: 'opica', p: 'foto:opica', b: 'prales' }, { n: 'papagáj', p: 'foto:papagaj', b: 'prales' }, { n: 'gorila', p: 'foto:gorila', b: 'prales' }, { n: 'leňochod', p: 'foto:lenochod', b: 'prales' },
        { n: 'ťava', p: 'foto:tava', b: 'pust' }, { n: 'škorpión', p: 'foto:skorpion', b: 'pust' },
      ],
    },
    quiz: [
      { q: 'Kde bývajú včely?', a: 'v úli', o: ['v nore', 'v brlohu', 'v maštali'] },
      { q: 'Čo vyrábajú včely?', a: 'med', o: ['mlieko', 'syr', 'vlnu'] },
      { q: 'Čo má ťava na chrbte?', a: 'hrby so zásobou tuku', o: ['krídla', 'pancier', 'ostne'], f: 'Vďaka tuku v hrboch vydrží ťava na púšti veľa dní bez jedla.' },
      { q: 'Kto si stavia hniezdo?', a: 'vtáky', o: ['ryby', 'krokodíly', 'kone'] },
      { q: 'Ktoré zviera žije v lese?', pics: true, a: 'foto:jelen', o: ['foto:tava', 'foto:chobotnica', 'foto:opica'] },
      { q: 'Ktoré zviera žije v mori?', pics: true, a: 'foto:chobotnica', o: ['foto:jezko', 'foto:krava', 'foto:veverica'] },
      { q: 'Aké je počasie na púšti?', a: 'horúco a sucho', o: ['sneží', 'stále prší', 'je tam zima ako v chladničke'] },
    ],
    tf: [
      { s: 'Veverička žije v lese.', ok: true },
      { s: 'Ryby žijú na púšti.', ok: false, f: 'Ryby žijú vo vode.' },
      { s: 'Opice žijú v pralese.', ok: true },
      { s: 'Líška si robí noru.', ok: true },
      { s: 'Ťava žije v mori.', ok: false, f: 'Ťava žije na púšti.' },
      { s: 'Včely bývajú v úli.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'sort', rounds: 10 },
      { type: 'balloons', rounds: 5 },
      { type: 'odd', rounds: 5 },
      { type: 'quiz', rounds: 5 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-plants', title: 'Rastliny', sub: 'časti rastliny, ovocie, zelenina', icon: '🌻', board: 'plant',
    badge: { e: '🌻', name: 'Malá záhradníčka', desc: 'Poznáš časti rastliny' },
    items: [
      { n: 'koreň', p: 'foto:koren', id: 'koren', f: 'Koreň drží rastlinu v zemi a pije vodu z pôdy.' },
      { n: 'stonka', p: 'foto:stonka', id: 'stonka', f: 'Stonka nesie listy a kvety a vedie hore vodu.' },
      { n: 'list', p: 'foto:list', id: 'list', f: 'Listy chytajú slnečné svetlo a vyrábajú z neho potravu pre rastlinu.' },
      { n: 'kvet', p: 'foto:kvet', id: 'kvet', f: 'Kvet voňia a láka včely. Tie prenášajú peľ z kvetu na kvet.' },
      { n: 'plod', p: 'foto:jablko', id: 'plod', f: 'Z kvetu vyrastie plod. V plode sú semienka.' },
      { n: 'semienko', p: 'foto:semienko', f: 'Zo semienka vyklíči nová rastlinka. Potrebuje vodu, teplo a svetlo.' },
    ],
    sort: {
      title: 'Ovocie alebo zelenina?',
      bins: [
        { id: 'ovocie', n: 'ovocie', p: '🍎' },
        { id: 'zelenina', n: 'zelenina', p: '🥕' },
      ],
      items: [
        { n: 'jablko', p: 'foto:jablko', b: 'ovocie' }, { n: 'hruška', p: 'foto:hruska', b: 'ovocie' }, { n: 'banán', p: 'foto:banan', b: 'ovocie' },
        { n: 'hrozno', p: 'foto:hrozno', b: 'ovocie' }, { n: 'jahoda', p: 'foto:jahoda', b: 'ovocie' }, { n: 'čerešne', p: 'foto:ceresne', b: 'ovocie' },
        { n: 'broskyňa', p: 'foto:broskyna', b: 'ovocie' }, { n: 'citrón', p: 'foto:citron', b: 'ovocie' }, { n: 'ananás', p: 'foto:ananas', b: 'ovocie' },
        { n: 'mrkva', p: 'foto:mrkva', b: 'zelenina' }, { n: 'zemiak', p: 'foto:zemiak', b: 'zelenina' }, { n: 'uhorka', p: 'foto:uhorka', b: 'zelenina' },
        { n: 'cibuľa', p: 'foto:cibula', b: 'zelenina' }, { n: 'brokolica', p: 'foto:brokolica', b: 'zelenina' }, { n: 'cesnak', p: 'foto:cesnak', b: 'zelenina' },
        { n: 'šalát', p: 'foto:salat', b: 'zelenina' }, { n: 'baklažán', p: 'foto:baklazan', b: 'zelenina' }, { n: 'paprika', p: 'foto:paprika', b: 'zelenina' },
      ],
    },
    quiz: [
      { q: 'Čo potrebuje rastlina, aby rástla?', a: 'vodu, svetlo a vzduch', o: ['čokoládu', 'tmu a ticho', 'len piesok'] },
      { q: 'Ktorá časť rastliny je pod zemou?', a: 'koreň', o: ['kvet', 'list', 'plod'] },
      { q: 'Čo zbierajú včely na kvetoch?', a: 'nektár a peľ', o: ['listy', 'kamienky', 'vodu z kaluží'] },
      { q: 'Z čoho vyrastie nová rastlina?', a: 'zo semienka', o: ['z kameňa', 'z listu papiera', 'z piesku'] },
      { q: 'Ktorá zelenina rastie pod zemou?', pics: true, a: 'foto:mrkva', o: ['foto:uhorka', 'foto:baklazan', 'foto:brokolica'] },
      { q: 'Na čom rastú jablká?', a: 'na strome', o: ['v zemi', 'na kríčku pri zemi', 'vo vode'] },
      { q: 'Akú farbu majú listy väčšiny rastlín?', a: 'zelenú', o: ['modrú', 'fialovú', 'čiernu'] },
      { q: 'Čo sa stane s rastlinou bez vody?', a: 'zvädne', o: ['rozkvitne', 'narastie', 'začne spievať'] },
    ],
    tf: [
      { s: 'Koreň je pod zemou.', ok: true },
      { s: 'Rastliny nepotrebujú vodu.', ok: false, f: 'Bez vody rastlina zvädne. Potrebuje aj svetlo a vzduch.' },
      { s: 'Jahoda je ovocie.', ok: true },
      { s: 'Mrkva je ovocie.', ok: false, f: 'Mrkva je zelenina – koreňová zelenina.' },
      { s: 'Zemiaky rastú pod zemou.', ok: true },
      { s: 'Včely pomáhajú kvetom.', ok: true, f: 'Včely prenášajú peľ, a tak z kvetov môžu vyrásť plody.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'map', rounds: 5, ask: 'Ukáž na obrázku: {n}' },
      { type: 'sort', rounds: 10 },
      { type: 'odd', rounds: 5 },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-seasons', title: 'Ročné obdobia', sub: 'jar, leto, jeseň, zima a mesiace', icon: '🍂',
    badge: { e: '🍂', name: 'Pani ročných období', desc: 'Poznáš ročné obdobia a mesiace' },
    items: [
      { n: 'jar', p: 'foto:jar', f: 'Príroda sa prebúdza, kvitnú snežienky a vracajú sa vtáky. Mesiace: marec, apríl, máj.' },
      { n: 'leto', p: 'foto:leto', f: 'Je teplo, sú prázdniny a dozrieva ovocie. Mesiace: jún, júl, august.' },
      { n: 'jeseň', p: 'foto:jesen', f: 'Listy menia farbu a padajú, zbierame gaštany. Mesiace: september, október, november.' },
      { n: 'zima', p: 'foto:zima', f: 'Sneží, stavajú sa snehuliaci a sú Vianoce. Mesiace: december, január, február.' },
    ],
    sort: {
      title: 'Kedy to býva?',
      bins: [
        { id: 'jar', n: 'jar', p: 'foto:jar' },
        { id: 'leto', n: 'leto', p: 'foto:leto' },
        { id: 'jesen', n: 'jeseň', p: 'foto:jesen' },
        { id: 'zima', n: 'zima', p: 'foto:zima' },
      ],
      items: [
        { n: 'snehuliak', p: 'foto:snehuliak', b: 'zima' }, { n: 'Vianoce', p: 'foto:vianoce', b: 'zima' }, { n: 'sánkovanie', p: 'foto:sankovanie', b: 'zima' }, { n: 'lyžovanie', p: 'foto:lyzovanie', b: 'zima' },
        { n: 'tulipány', p: 'foto:tulipany', b: 'jar' }, { n: 'Veľká noc', p: 'foto:velka-noc', b: 'jar' }, { n: 'kvitnúce stromy', p: 'foto:kvitnuce-stromy', b: 'jar' },
        { n: 'kúpanie pri mori', p: 'foto:more', b: 'leto' }, { n: 'prázdniny', p: 'foto:prazdniny', b: 'leto' }, { n: 'melón', p: 'foto:melon', b: 'leto' },
        { n: 'padajúce lístie', p: 'foto:listie', b: 'jesen' }, { n: 'gaštany', p: 'foto:gastany', b: 'jesen' }, { n: 'tekvica', p: 'foto:tekvica', b: 'jesen' }, { n: 'huby', p: 'foto:huby', b: 'jesen' },
      ],
    },
    order: [
      { q: 'Zoraď ročné obdobia – začni jarou', seq: [{ n: 'jar', p: 'foto:jar' }, { n: 'leto', p: 'foto:leto' }, { n: 'jeseň', p: 'foto:jesen' }, { n: 'zima', p: 'foto:zima' }] },
      { q: 'Zoraď mesiace od januára', seq: [{ n: 'január' }, { n: 'február' }, { n: 'marec' }, { n: 'apríl' }, { n: 'máj' }, { n: 'jún' }] },
      { q: 'Zoraď mesiace od júla', seq: [{ n: 'júl' }, { n: 'august' }, { n: 'september' }, { n: 'október' }, { n: 'november' }, { n: 'december' }] },
      { q: 'Zoraď jesenné mesiace', seq: [{ n: 'september' }, { n: 'október' }, { n: 'november' }] },
      { q: 'Zoraď zimné mesiace', seq: [{ n: 'december' }, { n: 'január' }, { n: 'február' }] },
    ],
    quiz: [
      { q: 'Koľko mesiacov má rok?', a: '12', o: ['10', '7', '4'] },
      { q: 'Koľko ročných období máme?', a: '4', o: ['2', '12', '7'] },
      { q: 'Kedy sú Vianoce?', a: 'v zime', o: ['v lete', 'na jar', 'na jeseň'] },
      { q: 'Kedy začína škola?', a: 'v septembri', o: ['v januári', 'v júli', 'v máji'] },
      { q: 'Ktorý mesiac je prvý v roku?', a: 'január', o: ['marec', 'september', 'december'] },
      { q: 'Ktoré ročné obdobie príde po lete?', a: 'jeseň', o: ['jar', 'zima', 'znova leto'] },
      { q: 'Ktorý mesiac je posledný v roku?', a: 'december', o: ['november', 'január', 'jún'] },
      { q: 'Kedy odlietajú lastovičky do teplých krajín?', a: 'na jeseň', o: ['na jar', 'v lete', 'nikdy'] },
      { q: 'Ktoré obdobie má letné prázdniny?', a: 'leto', o: ['zima', 'jar', 'jeseň'] },
    ],
    tf: [
      { s: 'V zime sneží.', ok: true },
      { s: 'Snežienky kvitnú na jeseň.', ok: false, f: 'Snežienky kvitnú na jar – sú medzi prvými kvietkami.' },
      { s: 'Rok má 12 mesiacov.', ok: true },
      { s: 'Po zime príde jar.', ok: true },
      { s: 'Letné prázdniny sú v decembri.', ok: false, f: 'Letné prázdniny sú v júli a v auguste.' },
      { s: 'Na jeseň padá lístie zo stromov.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'sort', rounds: 10 },
      { type: 'order', rounds: 3 },
      { type: 'quiz', rounds: 6 },
      { type: 'balloons', rounds: 5 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-animals', title: 'Zvieracia ríša', sub: 'cicavce, vtáky, ryby, hmyz, plazy', icon: '🐾',
    badge: { e: '🐞', name: 'Malá zoologička', desc: 'Vieš triediť zvieratá' },
    items: [
      { n: 'cicavce', p: 'foto:mama-krava', f: 'Mláďatá pijú mamičkino mlieko. Väčšina má srsť. Aj človek je cicavec!' },
      { n: 'vtáky', p: 'foto:hniezdo', f: 'Majú perie, zobák a krídla. Liahnu sa z vajíčok.' },
      { n: 'ryby', p: 'foto:kapor', f: 'Žijú vo vode, dýchajú žiabrami a majú šupiny a plutvy.' },
      { n: 'hmyz', p: 'foto:lienka', f: 'Má 6 nôh. Pavúk nie je hmyz – má 8 nôh!' },
      { n: 'plazy', p: 'foto:jasterica', f: 'Majú suchú šupinatú kožu a kladú vajíčka. Napríklad had, korytnačka či krokodíl.' },
      { n: 'obojživelníky', p: 'foto:zaba', f: 'Žijú vo vode aj na súši – napríklad žaba.' },
    ],
    sort: {
      title: 'Kto je to?',
      bins: [
        { id: 'cic', n: 'cicavec', p: '🐄' },
        { id: 'vtak', n: 'vták', p: '🐦' },
        { id: 'ryba', n: 'ryba', p: '🐟' },
        { id: 'hmyz', n: 'hmyz', p: '🐞' },
        { id: 'plaz', n: 'plaz', p: '🦎' },
      ],
      items: [
        { n: 'pes', p: 'foto:pes', b: 'cic' }, { n: 'slon', p: 'foto:slon', b: 'cic' }, { n: 'zajac', p: 'foto:zajac', b: 'cic' },
        { n: 'delfín', p: 'foto:delfin', b: 'cic', f: 'Delfín žije vo vode, ale je to cicavec – dýcha vzduch.' },
        { n: 'netopier', p: 'foto:netopier', b: 'cic', f: 'Netopier lieta, ale nie je vták – je to cicavec.' },
        { n: 'veľryba', p: 'foto:velryba', b: 'cic', f: 'Veľryba je cicavec – mláďatá pijú mlieko.' },
        { n: 'orol', p: 'foto:orol', b: 'vtak' }, { n: 'sova', p: 'foto:sova', b: 'vtak' }, { n: 'papagáj', p: 'foto:papagaj', b: 'vtak' },
        { n: 'tučniak', p: 'foto:tucniak', b: 'vtak', f: 'Tučniak nelieta, ale je to vták – má perie a zobák.' },
        { n: 'žralok', p: 'foto:zralok', b: 'ryba' }, { n: 'rybka', p: 'foto:rybka', b: 'ryba' }, { n: 'kapor', p: 'foto:kapor', b: 'ryba' },
        { n: 'včela', p: 'foto:vcela', b: 'hmyz' }, { n: 'lienka', p: 'foto:lienka', b: 'hmyz' }, { n: 'motýľ', p: 'foto:motyl', b: 'hmyz' }, { n: 'mravec', p: 'foto:mravec', b: 'hmyz' },
        { n: 'had', p: 'foto:had', b: 'plaz' }, { n: 'korytnačka', p: 'foto:korytnacka', b: 'plaz' }, { n: 'krokodíl', p: 'foto:krokodil', b: 'plaz' }, { n: 'jašterica', p: 'foto:jasterica', b: 'plaz' },
      ],
    },
    quiz: [
      { q: 'Koľko nôh má hmyz?', a: '6', o: ['4', '8', '2'] },
      { q: 'Koľko nôh má pavúk?', a: '8', o: ['6', '4', '10'], f: 'Pavúk má 8 nôh, preto nie je hmyz.' },
      { q: 'Je delfín ryba?', a: 'nie, je to cicavec', o: ['áno, je to ryba', 'je to vták'] },
      { q: 'Čím dýchajú ryby?', a: 'žiabrami', o: ['nosom', 'ušami', 'krídlami'] },
      { q: 'Ktoré zviera je cicavec?', pics: true, a: 'foto:netopier', o: ['foto:orol', 'foto:had', 'foto:ryba'], f: 'Netopier je lietajúci cicavec.' },
      { q: 'Ktorý vták nevie lietať?', pics: true, a: 'foto:tucniak', o: ['foto:orol', 'foto:sova', 'foto:papagaj'] },
      { q: 'Čo majú všetky vtáky?', a: 'perie a zobák', o: ['srsť a fúzy', 'šupiny a plutvy', 'pancier'] },
      { q: 'Ktoré zviera je hmyz?', pics: true, a: 'foto:mravec', o: ['foto:pavuk', 'foto:slimak', 'foto:had'], f: 'Mravec má 6 nôh – je to hmyz. Pavúk má 8 nôh a slimák nemá žiadne.' },
    ],
    tf: [
      { s: 'Netopier je vták.', ok: false, f: 'Netopier je cicavec, hoci lieta.' },
      { s: 'Pavúk je hmyz.', ok: false, f: 'Pavúk má 8 nôh, hmyz má 6.' },
      { s: 'Veľryba je cicavec.', ok: true },
      { s: 'Tučniak je vták.', ok: true },
      { s: 'Had má štyri nohy.', ok: false, f: 'Had nemá žiadne nohy – plazí sa.' },
      { s: 'Človek je cicavec.', ok: true },
      { s: 'Ryby majú perie.', ok: false, f: 'Ryby majú šupiny. Perie majú vtáky.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'sort', rounds: 10 },
      { type: 'quiz', rounds: 6 },
      { type: 'odd', rounds: 5 },
      { type: 'balloons', rounds: 5 },
      { type: 'tf', rounds: 7 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-cycle', title: 'Ako rastieme', sub: 'z vajíčka motýľ', icon: '🦋',
    badge: { e: '🦋', name: 'Pani motýlica', desc: 'Poznáš, ako sa rodí život' },
    items: [
      { n: 'motýľ', p: 'row:foto:motyl-vajicka|foto:husenica|foto:kukla|foto:motyl', f: 'Z vajíčka sa vyliahne húsenica. Tá sa zakuklí a z kukly vyletí motýľ.' },
      { n: 'žaba', p: 'row:foto:zabie-vajicka|foto:zubrienka|foto:zaba', f: 'Zo žabích vajíčok sú žubrienky. Narastú im nohy, stratia chvost – a je z nich žaba.' },
      { n: 'sliepka', p: 'row:foto:vajicko|foto:liahnutie|foto:kuriatko|foto:sliepka', f: 'Sliepka sedí na vajíčkach. Vyliahne sa kuriatko a z neho vyrastie sliepka alebo kohút.' },
      { n: 'rastlina', p: 'row:foto:semienko|foto:klicok|foto:rastlinka|foto:slnecnica', f: 'Zo semienka vyklíči klíček, vyrastie rastlinka a rozkvitne.' },
      { n: 'človek', p: 'row:👶|🧒|🧑|🧓', f: 'Bábätko rastie – je z neho dieťa, potom dospelý a raz starký či starká.' },
    ],
    order: [
      { q: 'Ako vzniká motýľ?', seq: [{ n: 'vajíčko', p: 'foto:motyl-vajicka' }, { n: 'húsenica', p: 'foto:husenica' }, { n: 'kukla', p: 'foto:kukla' }, { n: 'motýľ', p: 'foto:motyl' }] },
      { q: 'Ako vzniká žaba?', seq: [{ n: 'vajíčka', p: 'foto:zabie-vajicka' }, { n: 'žubrienka', p: 'foto:zubrienka' }, { n: 'žubrienka s nožičkami', p: 'foto:zubrienka-nozicky' }, { n: 'žaba', p: 'foto:zaba' }] },
      { q: 'Ako rastie kuriatko?', seq: [{ n: 'vajíčko', p: 'foto:vajicko' }, { n: 'liahnutie', p: 'foto:liahnutie' }, { n: 'kuriatko', p: 'foto:kuriatko' }, { n: 'sliepka', p: 'foto:sliepka' }] },
      { q: 'Ako rastie kvietok?', seq: [{ n: 'semienko', p: 'foto:semienko' }, { n: 'klíček', p: 'foto:klicok' }, { n: 'rastlinka', p: 'foto:rastlinka' }, { n: 'kvet', p: 'foto:slnecnica' }] },
      { q: 'Ako rastie človek?', seq: [{ n: 'bábätko', p: '👶' }, { n: 'dieťa', p: '🧒' }, { n: 'dospelý', p: '🧑' }, { n: 'starký', p: '🧓' }] },
      { q: 'Ako rastie jablko?', seq: [{ n: 'kvet', p: 'foto:jablon-kvet' }, { n: 'malé jabĺčko', p: 'foto:male-jablcko' }, { n: 'zrelé jablko', p: 'foto:jablko' }] },
    ],
    quiz: [
      { q: 'Z čoho sa vyliahne húsenica?', a: 'z vajíčka', o: ['z kvetu', 'z kukly', 'zo semienka'] },
      { q: 'Čo vyletí z kukly?', a: 'motýľ', o: ['včela', 'vták', 'lienka'] },
      { q: 'Ako sa volá mláďa žaby?', a: 'žubrienka', o: ['húsenica', 'kuriatko', 'rybka'] },
      { q: 'Čo potrebuje semienko, aby vyklíčilo?', a: 'vodu a teplo', o: ['sneh a mráz', 'tmu a sucho', 'soľ'] },
      { q: 'Čo stratí žubrienka, keď sa mení na žabu?', a: 'chvost', o: ['nohy', 'oči', 'ústa'] },
      { q: 'Čo sa stane z húsenice?', a: 'kukla a potom motýľ', o: ['had', 'žaba', 'dážďovka'] },
    ],
    tf: [
      { s: 'Motýľ sa vyliahne priamo z vajíčka.', ok: false, f: 'Z vajíčka je najprv húsenica, potom kukla a až potom motýľ.' },
      { s: 'Žubrienka žije vo vode.', ok: true },
      { s: 'Kuriatko sa liahne z vajíčka.', ok: true },
      { s: 'Zo semienka môže vyrásť strom.', ok: true, f: 'Aj obrovský dub vyrástol zo žaluďa – semienka.' },
      { s: 'Žaba má v dospelosti dlhý rybí chvost.', ok: false, f: 'Chvost má len žubrienka. Dospelá žaba ho už nemá.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'order', rounds: 4 },
      { type: 'quiz', rounds: 5 },
      { type: 'order', rounds: 3 },
      { type: 'tf', rounds: 5 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-waste', title: 'Triedime odpad', sub: 'farebné kontajnery', icon: '♻️',
    badge: { e: '♻️', name: 'Ochrankyňa Zeme', desc: 'Vieš správne triediť odpad' },
    items: [
      { n: 'plasty', p: 'bin:yellow', f: 'Do žltého kontajnera patria plasty: fľaše od nápojov, kelímky, fólie a vrecká.' },
      { n: 'papier', p: 'bin:blue', f: 'Do modrého kontajnera patrí papier: noviny, zošity, krabice a obaly z papiera.' },
      { n: 'sklo', p: 'bin:green', f: 'Do zeleného kontajnera patria sklenené fľaše a poháre od zaváranín.' },
      { n: 'kovy', p: 'bin:red', f: 'Do červeného kontajnera patria kovy: plechovky a alobal.' },
      { n: 'bioodpad', p: 'bin:brown', f: 'Do hnedého kontajnera patria šupky, zvyšky ovocia a zeleniny a lístie.' },
      { n: 'Prečo triedime?', p: '🌍', f: 'Z vytriedeného odpadu sa vyrobia nové veci. Príroda je čistejšia a netreba toľko skládok.' },
    ],
    sort: {
      title: 'Do ktorého kontajnera?',
      bins: [
        { id: 'plast', n: 'plasty', p: 'bin:yellow' },
        { id: 'papier', n: 'papier', p: 'bin:blue' },
        { id: 'sklo', n: 'sklo', p: 'bin:green' },
        { id: 'kov', n: 'kovy', p: 'bin:red' },
        { id: 'bio', n: 'bioodpad', p: 'bin:brown' },
      ],
      items: [
        { n: 'plastová fľaša', p: 'svg:pet', b: 'plast' }, { n: 'fľaša od šampónu', p: '🧴', b: 'plast' }, { n: 'plastový kelímok', p: '🥤', b: 'plast' },
        { n: 'noviny', p: '📰', b: 'papier' }, { n: 'krabica', p: '📦', b: 'papier' }, { n: 'starý zošit', p: '📓', b: 'papier' }, { n: 'obálka', p: '✉️', b: 'papier' },
        { n: 'sklenená fľaša', p: 'svg:flasa', b: 'sklo' }, { n: 'pohár od zaváraniny', p: 'svg:zavaranina', b: 'sklo' }, { n: 'fľaša od sektu', p: '🍾', b: 'sklo' },
        { n: 'plechovka od limonády', p: 'svg:plechovka', b: 'kov' }, { n: 'konzerva', p: '🥫', b: 'kov' },
        { n: 'banánová šupka', p: '🍌', b: 'bio' }, { n: 'ohryzok z jablka', p: '🍏', b: 'bio' }, { n: 'lístie', p: '🍂', b: 'bio' }, { n: 'škrupinky z vajíčok', p: '🥚', b: 'bio' },
      ],
    },
    quiz: [
      { q: 'Akú farbu má kontajner na plasty?', a: 'žltú', o: ['modrú', 'zelenú', 'hnedú'] },
      { q: 'Akú farbu má kontajner na papier?', a: 'modrú', o: ['žltú', 'červenú', 'zelenú'] },
      { q: 'Akú farbu má kontajner na sklo?', a: 'zelenú', o: ['modrú', 'žltú', 'červenú'] },
      { q: 'Kam patrí banánová šupka?', a: 'do bioodpadu', o: ['do plastov', 'do skla', 'do papiera'] },
      { q: 'Prečo triedime odpad?', a: 'aby sa z neho vyrobili nové veci', o: ['aby bolo viac odpadu', 'lebo je to zábava pre smetiarov', 'aby sa pokazil'] },
      { q: 'Čo urobíme s plastovou fľašou pred vyhodením?', a: 'stlačíme ju', o: ['naplníme ju pieskom', 'dáme ju do rúry', 'zakopeme ju'], f: 'Stlačená fľaša zaberie v kontajneri menej miesta.' },
    ],
    tf: [
      { s: 'Noviny patria do modrého kontajnera.', ok: true },
      { s: 'Sklenená fľaša patrí do žltého kontajnera.', ok: false, f: 'Sklo patrí do zeleného kontajnera.' },
      { s: 'Z vytriedeného papiera sa dá vyrobiť nový papier.', ok: true },
      { s: 'Odpadky môžeme hádzať v lese na zem.', ok: false, f: 'Nikdy! Odpadky odnesieme domov alebo do koša.' },
      { s: 'Plechovka patrí do kontajnera na kovy.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'sort', rounds: 10 },
      { type: 'quiz', rounds: 6 },
      { type: 'sort', rounds: 12 },
      { type: 'tf', rounds: 5 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'nat-review', review: true, title: 'Prírodná výprava', sub: 'opakovanie prírody', icon: '🏆',
    badge: { e: '🌳', name: 'Kráľovná prírody', desc: 'Zvládla si celú prírodu!' },
    acts: [
      { type: 'bigquiz', rounds: 10 },
      { type: 'sort', rounds: 10, src: 'area' },
      { type: 'odd', rounds: 6, src: 'area' },
      { type: 'memory', pairs: 6, src: 'area' },
      { type: 'mix', rounds: 8, src: 'area' },
    ],
  },
]);
