/* ==========================================================================
   Oblasť: CESTOVATEĽKA (zemepis)
   Pri položkách mapy: id = štát / kontinent / oceán na mape, pt = [dĺžka, šírka] bodu, line = rieka
   ========================================================================== */
addLessons('geo', [
  /* ------------------------------------------------------------------ */
  {
    id: 'geo-sk', title: 'Moje Slovensko', sub: 'vlajka, znak, hymna', icon: 'flag:sk',
    badge: { e: 'svg:znak', name: 'Malá vlastenka', desc: 'Poznáš symboly Slovenska' },
    items: [
      { n: 'Slovenská vlajka', p: 'flag:sk', f: 'Má tri pruhy – biely, modrý a červený – a na nich štátny znak.' },
      { n: 'Štátny znak', p: 'svg:znak', f: 'Biely dvojkríž na troch modrých vŕškoch v červenom štíte.' },
      { n: 'Hymna', p: '🎵', f: 'Slovenská hymna sa volá „Nad Tatrou sa blýska“. Pri hymne stojíme.' },
      { n: 'Bratislava', p: 'foto:bratislava', f: 'Hlavné mesto Slovenska. Nad Dunajom stojí Bratislavský hrad.' },
      { n: 'Slovenčina', p: '🗣️', f: 'Na Slovensku hovoríme po slovensky. Slovenčina má aj písmená ä, ô a ľ.' },
      { n: 'Euro', p: 'coin:100', f: 'Na Slovensku platíme eurami. Jedno euro má 100 centov.' },
      { n: 'Vysoké Tatry', p: 'foto:vysoke-tatry', f: 'Najvyššie hory Slovenska. Najvyšší vrch je Gerlachovský štít – 2655 metrov.' },
      { n: 'Kriváň', p: 'pair:foto:krivan|coin:5', f: 'Slávny štít v Tatrách. Nájdeš ho na slovenských 1, 2 a 5-centových minciach.' },
      { n: 'Dunaj', p: 'pair:foto:dunaj|line:slovakia:dunaj', f: 'Najväčšia rieka, ktorá tečie cez Slovensko. Preteká aj cez Bratislavu.' },
      { n: 'Váh', p: 'pair:foto:vah|line:slovakia:vah', f: 'Najdlhšia slovenská rieka – má 403 kilometrov.' },
    ],
    quiz: [
      { q: 'Aké je hlavné mesto Slovenska?', a: 'Bratislava', o: ['Košice', 'Žilina', 'Praha'] },
      { q: 'Ktorá vlajka je slovenská?', pics: true, a: 'flag:sk', o: ['flag:si', 'flag:ru', 'flag:cz'], f: 'Pozor! Slovinská a ruská vlajka majú tie isté farby. Slovenskú spoznáš podľa dvojkríža.' },
      { q: 'Ako sa volá slovenská hymna?', a: 'Nad Tatrou sa blýska', o: ['Tancuj, tancuj', 'Kukulienka, kde si bola'] },
      { q: 'Aké farby má slovenská vlajka?', a: 'biela, modrá, červená', o: ['červená a biela', 'zelená, biela, červená', 'žltá a modrá'] },
      { q: 'Čím platíme na Slovensku?', a: 'eurami', o: ['korunami', 'dolármi', 'zlotými'] },
      { q: 'Aký je najvyšší vrch Slovenska?', a: 'Gerlachovský štít', o: ['Kriváň', 'Lomnický štít', 'Ďumbier'] },
      { q: 'Čo je na slovenskom štátnom znaku?', a: 'dvojkríž na troch vŕškoch', o: ['lev s korunou', 'orol', 'javorový list'] },
      { q: 'Na ktorom svetadiele leží Slovensko?', a: 'v Európe', o: ['v Ázii', 'v Afrike', 'v Amerike'] },
      { q: 'Kedy vznikla Slovenská republika?', a: '1. januára 1993', o: ['1. mája 2004', '24. decembra 1990', '1. septembra 2000'], f: 'Slovensko má narodeniny 1. januára. V roku 2004 sme vstúpili do Európskej únie.' },
      { q: 'Ktorá rieka je najdlhšia na Slovensku?', a: 'Váh', o: ['Hron', 'Morava', 'Nitra'] },
      { q: 'Ktorý štít je na 1, 2 a 5-centových minciach?', pics: false, a: 'Kriváň', o: ['Gerlachovský štít', 'Rysy', 'Chopok'] },
    ],
    tf: [
      { s: 'Slovensko má more.', ok: false, f: 'Slovensko nemá more. Najbližšie je Jadranské more v Chorvátsku.' },
      { s: 'Hlavné mesto Slovenska je Bratislava.', ok: true },
      { s: 'Na slovenskej vlajke je dvojkríž.', ok: true },
      { s: 'Na Slovensku platíme dolármi.', ok: false, f: 'Platíme eurami (€).' },
      { s: 'Vysoké Tatry sú najvyššie hory Slovenska.', ok: true },
      { s: 'Dunaj tečie cez Bratislavu.', ok: true },
      { s: 'Slovensko leží v Afrike.', ok: false, f: 'Slovensko leží v strede Európy.' },
      { s: 'Slovensko je v Európskej únii.', ok: true, f: 'Do Európskej únie sme vstúpili v roku 2004.' },
      { s: 'Pri hymne sa sedí a rozpráva.', ok: false, f: 'Pri hymne stojíme a sme ticho – z úcty k našej krajine.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'name', rounds: 6, opts: 3 },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 7 },
      { type: 'memory', pairs: 5 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-map', title: 'Mapa Slovenska', sub: 'mestá, hory a rieky', icon: '🗺️', board: 'slovakia',
    badge: { e: '🗺️', name: 'Slovenská cestovateľka', desc: 'Vyznáš sa na mape Slovenska' },
    items: [
      { n: 'Bratislava', p: 'foto:bratislava', pt: [17.107, 48.148], f: 'Hlavné a najväčšie mesto. Leží na Dunaji pri hraniciach s Rakúskom a Maďarskom.' },
      { n: 'Košice', p: 'foto:kosice', pt: [21.261, 48.716], f: 'Druhé najväčšie mesto, na východe Slovenska. Stojí tu veľký Dóm svätej Alžbety.' },
      { n: 'Prešov', p: 'foto:presov', pt: [21.239, 48.998], f: 'Mesto na východe, kúsok na sever od Košíc.' },
      { n: 'Žilina', p: 'foto:zilina', pt: [18.740, 49.223], f: 'Mesto na severe, pri rieke Váh a pri horách Malá Fatra.' },
      { n: 'Banská Bystrica', p: 'foto:banska-bystrica', pt: [19.146, 48.736], f: 'Mesto v strede Slovenska, pri rieke Hron.' },
      { n: 'Nitra', p: 'foto:nitra', pt: [18.087, 48.307], f: 'Jedno z najstarších miest Slovenska, pod vrchom Zobor.' },
      { n: 'Trnava', p: 'foto:trnava', pt: [17.588, 48.377], f: 'Volajú ju „malý Rím“, lebo má veľa kostolov.' },
      { n: 'Trenčín', p: 'foto:trencin', pt: [18.044, 48.894], f: 'Mesto s veľkým hradom na skale nad Váhom.' },
      { n: 'Vysoké Tatry', p: 'foto:vysoke-tatry', pt: [20.134, 49.164], f: 'Najvyššie hory Slovenska, na severe krajiny.' },
      { n: 'Dunaj', p: 'foto:dunaj', line: 'dunaj', f: 'Veľká rieka na juhu. Tvorí hranicu s Maďarskom.' },
      { n: 'Váh', p: 'foto:vah', line: 'vah', f: 'Najdlhšia slovenská rieka. Tečie cez Žilinu, Trenčín a Piešťany.' },
      { n: 'Hron', p: 'foto:hron', line: 'hron', f: 'Rieka, ktorá tečie cez Banskú Bystricu až do Dunaja.' },
    ],
    quiz: [
      { q: 'Ktoré mesto je hlavné mesto Slovenska?', a: 'Bratislava', o: ['Košice', 'Trnava', 'Žilina'] },
      { q: 'Ktoré mesto je na východe Slovenska?', a: 'Košice', o: ['Trnava', 'Bratislava', 'Trenčín'] },
      { q: 'Ktoré mesto volajú „malý Rím“?', a: 'Trnava', o: ['Nitra', 'Prešov', 'Žilina'] },
      { q: 'Kde sú Vysoké Tatry?', a: 'na severe Slovenska', o: ['na juhu Slovenska', 'pri Bratislave', 'pri mori'] },
      { q: 'Ktorá rieka tečie cez Bratislavu?', a: 'Dunaj', o: ['Váh', 'Hron', 'Hornád'] },
      { q: 'Cez ktoré mesto tečie rieka Hron?', a: 'Banská Bystrica', o: ['Košice', 'Trnava', 'Prešov'] },
      { q: 'Ktoré mesto je v strede Slovenska?', a: 'Banská Bystrica', o: ['Bratislava', 'Košice', 'Trnava'] },
      { q: 'Ktoré mesto má hrad nad riekou Váh?', a: 'Trenčín', o: ['Košice', 'Prešov', 'Nitra'] },
    ],
    tf: [
      { s: 'Bratislava leží na západe Slovenska.', ok: true },
      { s: 'Košice ležia pri Bratislave.', ok: false, f: 'Košice sú na východe, Bratislava na západe – ďaleko od seba.' },
      { s: 'Vysoké Tatry sú na severe Slovenska.', ok: true },
      { s: 'Dunaj tečie cez Košice.', ok: false, f: 'Dunaj tečie cez Bratislavu a Komárno. Cez Košice tečie Hornád.' },
      { s: 'Váh je najdlhšia slovenská rieka.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'map', rounds: 6, only: 'pt' },
      { type: 'quiz', rounds: 6 },
      { type: 'map', rounds: 8 },
      { type: 'tf', rounds: 5 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-neighbors', title: 'Naši susedia', sub: 'krajiny okolo Slovenska', icon: '🤝', board: 'central',
    badge: { e: '🤝', name: 'Dobrá susedka', desc: 'Poznáš všetkých susedov Slovenska' },
    items: [
      { n: 'Slovensko', p: 'flag:sk', id: 'sk', cap: 'Bratislava', gen: 'Slovenska', f: 'Naša krajina. Hlavné mesto je Bratislava.' },
      { n: 'Česko', p: 'flag:cz', id: 'cz', cap: 'Praha', gen: 'Česka', f: 'Kedysi sme boli jedna krajina – Československo. Hlavné mesto je Praha.' },
      { n: 'Poľsko', p: 'flag:pl', id: 'pl', cap: 'Varšava', gen: 'Poľska', f: 'Leží na sever od nás, za Tatrami. Hlavné mesto je Varšava.' },
      { n: 'Ukrajina', p: 'flag:ua', id: 'ua', cap: 'Kyjev', gen: 'Ukrajiny', f: 'Náš najväčší sused, na východe. Hlavné mesto je Kyjev.' },
      { n: 'Maďarsko', p: 'flag:hu', id: 'hu', cap: 'Budapešť', gen: 'Maďarska', f: 'Leží na juh od nás. Hlavné mesto Budapešť stojí na Dunaji.' },
      { n: 'Rakúsko', p: 'flag:at', id: 'at', cap: 'Viedeň', gen: 'Rakúska', f: 'Leží na západ od nás. Viedeň je od Bratislavy len asi 60 kilometrov.' },
    ],
    quiz: [
      { q: 'Koľko susedov má Slovensko?', a: '5', o: ['3', '4', '7'], f: 'Česko, Poľsko, Ukrajina, Maďarsko a Rakúsko.' },
      { q: 'Ktorý sused je najväčší?', a: 'Ukrajina', o: ['Rakúsko', 'Česko', 'Maďarsko'] },
      { q: 'Ktorý sused leží na sever od Slovenska?', a: 'Poľsko', o: ['Maďarsko', 'Rakúsko', 'Česko'] },
      { q: 'Ktorý sused leží na juh od Slovenska?', a: 'Maďarsko', o: ['Poľsko', 'Ukrajina', 'Česko'] },
      { q: 'S ktorou krajinou sme kedysi tvorili Československo?', a: 's Českom', o: ['s Poľskom', 's Rakúskom', 's Maďarskom'] },
      { q: 'Hlavné mesto ktorého suseda je najbližšie k Bratislave?', a: 'Viedeň', o: ['Praha', 'Varšava', 'Kyjev'] },
      { q: 'Ktorá vlajka je poľská?', pics: true, a: 'flag:pl', o: ['flag:at', 'flag:ua', 'flag:hu'], f: 'Poľská vlajka je biela a červená, rakúska červená, biela, červená.' },
      { q: 'Ktorá vlajka je ukrajinská?', pics: true, a: 'flag:ua', o: ['flag:pl', 'flag:cz', 'flag:sk'], f: 'Modrá ako obloha a žltá ako obilné pole.' },
      { q: 'Cez ktoré hlavné mestá tečie Dunaj?', a: 'Viedeň, Bratislava, Budapešť', o: ['Praha a Varšava', 'Kyjev a Praha', 'Varšava a Viedeň'] },
    ],
    tf: [
      { s: 'Česko je sused Slovenska.', ok: true },
      { s: 'Nemecko je sused Slovenska.', ok: false, f: 'Nemecko susedí s Českom, Poľskom a Rakúskom, ale nie so Slovenskom.' },
      { s: 'Hlavné mesto Poľska je Varšava.', ok: true },
      { s: 'Hlavné mesto Maďarska je Viedeň.', ok: false, f: 'Hlavné mesto Maďarska je Budapešť. Viedeň je v Rakúsku.' },
      { s: 'Ukrajina leží na východ od Slovenska.', ok: true },
      { s: 'Praha je hlavné mesto Česka.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'find', rounds: 6, opts: 4, ask: 'Ktorá vlajka patrí krajine: {n}?' },
      { type: 'map', rounds: 6 },
      { type: 'match', pairs: 5, a: 'n', b: 'cap', title: 'Priraď hlavné mesto' },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-continents', title: 'Svetadiely', sub: 'sedem kontinentov', icon: '🌎', board: 'world',
    badge: { e: '🌎', name: 'Objaviteľka sveta', desc: 'Poznáš všetkých 7 svetadielov' },
    items: [
      { n: 'Európa', p: 'map:world:#eu', id: '#eu', f: 'Tu žijeme my! Je to malý svetadiel, ale žije v ňom veľa ľudí.' },
      { n: 'Ázia', p: 'map:world:#as', id: '#as', f: 'Najväčší svetadiel. Žije tu najviac ľudí na svete.' },
      { n: 'Afrika', p: 'map:world:#af', id: '#af', f: 'Horúci svetadiel s púšťou Sahara, žirafami, slonmi a levmi.' },
      { n: 'Severná Amerika', p: 'map:world:#na', id: '#na', f: 'Sú tu Kanada, USA a Mexiko. Patrí k nej aj veľký ľadový ostrov Grónsko.' },
      { n: 'Južná Amerika', p: 'map:world:#sa', id: '#sa', f: 'Rastie tu najväčší prales na svete – Amazonský prales.' },
      { n: 'Austrália', p: 'map:world:#oc', id: '#oc', f: 'Najmenší svetadiel. S ostrovmi okolo sa volá aj Oceánia. Žijú tu klokany.' },
      { n: 'Antarktída', p: 'map:world:#an', id: '#an', f: 'Najchladnejší svetadiel, celý pod ľadom. Žijú tu tučniaky, ale nie ľudia.' },
    ],
    sort: {
      title: 'Kde žije toto zvieratko?',
      bins: [
        { id: 'af', n: 'Afrika', p: '🌍' },
        { id: 'as', n: 'Ázia', p: '🏯' },
        { id: 'oc', n: 'Austrália', p: '🦘' },
        { id: 'sa', n: 'Južná Amerika', p: '🌴' },
        { id: 'an', n: 'Antarktída', p: '🧊' },
      ],
      items: [
        { n: 'lev', p: 'foto:lev', b: 'af' }, { n: 'žirafa', p: 'foto:zirafa', b: 'af' }, { n: 'zebra', p: 'foto:zebra', b: 'af' },
        { n: 'panda', p: 'foto:panda', b: 'as' }, { n: 'tiger', p: 'foto:tiger', b: 'as' },
        { n: 'klokan', p: 'foto:klokan', b: 'oc' }, { n: 'koala', p: 'foto:koala', b: 'oc' },
        { n: 'lama', p: 'foto:lama', b: 'sa' }, { n: 'leňochod', p: 'foto:lenochod', b: 'sa' },
        { n: 'tučniak cisársky', p: 'foto:tucniak', b: 'an' },
      ],
    },
    quiz: [
      { q: 'Koľko svetadielov je na Zemi?', a: '7', o: ['5', '4', '10'] },
      { q: 'Ktorý svetadiel je najväčší?', a: 'Ázia', o: ['Európa', 'Afrika', 'Austrália'] },
      { q: 'Na ktorom svetadiele žijeme my?', a: 'v Európe', o: ['v Ázii', 'v Amerike', 'v Afrike'] },
      { q: 'Ktorý svetadiel je celý pod ľadom?', a: 'Antarktída', o: ['Európa', 'Afrika', 'Austrália'] },
      { q: 'Kde je púšť Sahara?', a: 'v Afrike', o: ['v Európe', 'v Antarktíde', 'v Austrálii'] },
      { q: 'Ktorý svetadiel je najmenší?', a: 'Austrália', o: ['Európa', 'Ázia', 'Južná Amerika'] },
      { q: 'Kde rastie Amazonský prales?', a: 'v Južnej Amerike', o: ['v Európe', 'v Severnej Amerike', 'v Ázii'] },
      { q: 'Kde žijú klokany?', a: 'v Austrálii', o: ['v Afrike', 'v Európe', 'v Antarktíde'] },
    ],
    tf: [
      { s: 'Ázia je najväčší svetadiel.', ok: true },
      { s: 'V Antarktíde žijú levy.', ok: false, f: 'Levy žijú v teplej Afrike. V Antarktíde žijú tučniaky.' },
      { s: 'Slovensko leží v Európe.', ok: true },
      { s: 'Amerika sú vlastne dva svetadiely – Severná a Južná.', ok: true },
      { s: 'Austrália je zároveň krajina aj svetadiel.', ok: true },
      { s: 'Na svete je 12 svetadielov.', ok: false, f: 'Svetadielov je 7.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'map', rounds: 7 },
      { type: 'sort', rounds: 8 },
      { type: 'quiz', rounds: 6 },
      { type: 'mapname', rounds: 6, opts: 4 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-oceans', title: 'Oceány', sub: 'veľká modrá voda', icon: '🌊', board: 'world',
    badge: { e: '🐳', name: 'Morská víla', desc: 'Poznáš oceány sveta' },
    items: [
      { n: 'Tichý oceán', p: '🌊', id: 'pacific', f: 'Najväčší a najhlbší oceán. Je väčší ako všetka pevnina na Zemi dokopy!' },
      { n: 'Atlantický oceán', p: '⛵', id: 'atlantic', f: 'Oddeľuje Európu a Afriku od Ameriky. Druhý najväčší oceán.' },
      { n: 'Indický oceán', p: '🐠', id: 'indian', f: 'Najteplejší oceán. Leží medzi Afrikou, Áziou a Austráliou.' },
      { n: 'Severný ľadový oceán', p: '🧊', id: 'arctic', f: 'Najmenší oceán, pri severnom póle. Plávajú v ňom ľadové kryhy a žijú pri ňom ľadové medvede.' },
      { n: 'Južný oceán', p: '🐧', id: 'southern', f: 'Studený oceán okolo Antarktídy.' },
    ],
    quiz: [
      { q: 'Ktorý oceán je najväčší?', a: 'Tichý', o: ['Atlantický', 'Indický', 'Severný ľadový'] },
      { q: 'Ktorý oceán je najmenší?', a: 'Severný ľadový', o: ['Tichý', 'Atlantický', 'Indický'] },
      { q: 'Cez ktorý oceán sa plaví loďou z Európy do Ameriky?', a: 'cez Atlantický', o: ['cez Tichý', 'cez Indický', 'cez Južný'] },
      { q: 'Aká je voda v oceáne?', a: 'slaná', o: ['sladká', 'kyslá', 'horká ako čaj'] },
      { q: 'Koľko Zeme pokrýva voda?', a: 'väčšinu – asi 7 dielov z 10', o: ['polovicu', 'len malý kúsok', 'nič'], f: 'Preto Zem z vesmíru vyzerá modrá – „modrá planéta“.' },
      { q: 'Aké najväčšie zviera na svete žije v oceáne?', a: 'modrá veľryba', o: ['žralok', 'chobotnica', 'delfín'], f: 'Modrá veľryba je dlhá skoro ako tri autobusy – je to najväčšie zviera, aké kedy žilo.' },
      { q: 'Ktorý oceán je najteplejší?', a: 'Indický', o: ['Severný ľadový', 'Južný', 'Atlantický'] },
      { q: 'Ktorý oceán je okolo Antarktídy?', a: 'Južný', o: ['Indický', 'Severný ľadový', 'Atlantický'] },
    ],
    tf: [
      { s: 'V oceáne je slaná voda.', ok: true },
      { s: 'Atlantický oceán je najväčší.', ok: false, f: 'Najväčší je Tichý oceán.' },
      { s: 'Severný ľadový oceán je pri severnom póle.', ok: true },
      { s: 'Slovensko leží pri oceáne.', ok: false, f: 'Slovensko je v strede Európy, ďaleko od oceánov aj mora.' },
      { s: 'Voda pokrýva väčšiu časť Zeme ako pevnina.', ok: true },
      { s: 'Delfín je ryba.', ok: false, f: 'Delfín je cicavec – dýcha vzduch a mláďatá pijú mlieko.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'map', rounds: 6 },
      { type: 'quiz', rounds: 6 },
      { type: 'mapname', rounds: 5, opts: 4 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-europe', title: 'Krajiny Európy', sub: 'vlajky a hlavné mestá', icon: 'flag:eu', board: 'europe',
    badge: { e: 'flag:eu', name: 'Európanka', desc: 'Poznáš vlajky Európy' },
    items: [
      { n: 'Nemecko', p: 'flag:de', id: 'de', cap: 'Berlín', f: 'Veľká krajina so slávnymi autami a rozprávkovými zámkami. Hlavné mesto je Berlín.' },
      { n: 'Francúzsko', p: 'flag:fr', id: 'fr', cap: 'Paríž', f: 'V hlavnom meste Paríž stojí Eiffelova veža.' },
      { n: 'Taliansko', p: 'flag:it', id: 'it', cap: 'Rím', f: 'Tvarom pripomína čižmu! Odtiaľ pochádza pizza.' },
      { n: 'Španielsko', p: 'flag:es', id: 'es', cap: 'Madrid', f: 'Slnečná krajina s tancom flamenco. Hlavné mesto je Madrid.' },
      { n: 'Veľká Británia', p: 'flag:gb', id: 'gb', cap: 'Londýn', f: 'Ostrovná krajina, kde vládne kráľ. Hovorí sa tu po anglicky.' },
      { n: 'Chorvátsko', p: 'flag:hr', id: 'hr', cap: 'Záhreb', f: 'Má krásne Jadranské more – veľa Slovákov sem chodí na dovolenku.' },
      { n: 'Grécko', p: 'flag:gr', id: 'gr', cap: 'Atény', f: 'Krajina starých báji a ostrovov. Odtiaľ pochádzajú olympijské hry.' },
      { n: 'Holandsko', p: 'flag:nl', id: 'nl', cap: 'Amsterdam', f: 'Krajina tulipánov, veterných mlynov a bicyklov.' },
      { n: 'Švajčiarsko', p: 'flag:ch', id: 'ch', cap: 'Bern', f: 'Vysoké hory Alpy, syr s dierami a čokoláda. Vlajka je štvorcová!' },
      { n: 'Švédsko', p: 'flag:se', id: 'se', cap: 'Štokholm', f: 'Severská krajina, odkiaľ pochádza Pipi Dlhá Pančucha.' },
      { n: 'Nórsko', p: 'flag:no', id: 'no', cap: 'Oslo', f: 'Krajina hlbokých morských zálivov – fjordov – a polárnej žiary.' },
      { n: 'Portugalsko', p: 'flag:pt', id: 'pt', cap: 'Lisabon', f: 'Leží na úplnom západe Európy, pri Atlantickom oceáne.' },
    ],
    quiz: [
      { q: 'Ktorá krajina má tvar čižmy?', a: 'Taliansko', o: ['Španielsko', 'Nórsko', 'Grécko'] },
      { q: 'V ktorom meste stojí Eiffelova veža?', a: 'v Paríži', o: ['v Londýne', 'v Ríme', 'v Berlíne'] },
      { q: 'Kam chodí veľa Slovákov k moru?', a: 'do Chorvátska', o: ['do Švajčiarska', 'do Rakúska', 'do Česka'] },
      { q: 'Ktorá vlajka je francúzska?', pics: true, a: 'flag:fr', o: ['flag:it', 'flag:nl', 'flag:ie'], f: 'Francúzska vlajka: modrá, biela, červená – zvislé pruhy.' },
      { q: 'Ktorá vlajka je talianska?', pics: true, a: 'flag:it', o: ['flag:ie', 'flag:fr', 'flag:hu'], f: 'Talianska vlajka: zelená, biela, červená. Írska je zelená, biela, oranžová.' },
      { q: 'Ktorá vlajka je nemecká?', pics: true, a: 'flag:de', o: ['flag:be', 'flag:es', 'flag:ro'], f: 'Nemecká vlajka má vodorovné pruhy: čierny, červený a zlatý.' },
      { q: 'Kde sa hovorí po anglicky?', a: 'vo Veľkej Británii', o: ['vo Francúzsku', 'v Taliansku', 'v Nemecku'] },
      { q: 'Odkiaľ pochádzajú olympijské hry?', a: 'z Grécka', o: ['zo Švédska', 'z Holandska', 'z Portugalska'] },
      { q: 'Aké hory sú vo Švajčiarsku?', a: 'Alpy', o: ['Tatry', 'Himaláje', 'Karpaty'] },
      { q: 'Aká je vlajka Európskej únie?', pics: true, a: 'flag:eu', o: ['flag:se', 'flag:gr', 'flag:us'], f: 'Modrá vlajka s 12 zlatými hviezdami do kruhu.' },
    ],
    tf: [
      { s: 'Hlavné mesto Francúzska je Paríž.', ok: true },
      { s: 'Taliansko má tvar čižmy.', ok: true },
      { s: 'Hlavné mesto Nemecka je Viedeň.', ok: false, f: 'Hlavné mesto Nemecka je Berlín. Viedeň je v Rakúsku.' },
      { s: 'Švajčiarska vlajka je štvorcová.', ok: true },
      { s: 'Vo Veľkej Británii vládne kráľ.', ok: true },
      { s: 'Pizza pochádza zo Švédska.', ok: false, f: 'Pizza pochádza z Talianska.' },
      { s: 'Holandsko je krajina tulipánov a veterných mlynov.', ok: true },
    ],
    acts: [
      { type: 'learn' },
      { type: 'find', rounds: 6, opts: 4, ask: 'Ktorá vlajka patrí krajine: {n}?' },
      { type: 'map', rounds: 8 },
      { type: 'memory', pairs: 6 },
      { type: 'name', rounds: 6, opts: 3, show: 'n', ans: 'cap', ask: 'Aké je hlavné mesto krajiny {n}?', title: 'Hlavné mestá' },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-world', title: 'Veľké krajiny sveta', sub: 'vlajky celého sveta', icon: '🌏', board: 'world',
    badge: { e: '🌏', name: 'Svetobežníčka', desc: 'Poznáš veľké krajiny sveta' },
    items: [
      { n: 'Rusko', p: 'flag:ru', id: 'ru', cap: 'Moskva', f: 'Najväčšia krajina na svete – leží v Európe aj v Ázii.' },
      { n: 'Kanada', p: 'flag:ca', id: 'ca', cap: 'Ottawa', f: 'Druhá najväčšia krajina. Na vlajke má javorový list.' },
      { n: 'USA', p: 'flag:us', id: 'us', cap: 'Washington', f: 'Spojené štáty americké majú 50 štátov – a preto 50 hviezd na vlajke.' },
      { n: 'Čína', p: 'flag:cn', id: 'cn', cap: 'Peking', f: 'Je tu Veľký čínsky múr a v horách žijú pandy.' },
      { n: 'Brazília', p: 'flag:br', id: 'br', cap: 'Brazília', f: 'Najväčšia krajina Južnej Ameriky, s pralesom a vášňou pre futbal.' },
      { n: 'Austrália', p: 'flag:au', id: 'au', cap: 'Canberra', f: 'Krajina aj svetadiel zároveň! Žijú tu klokany a koaly.' },
      { n: 'India', p: 'flag:in', id: 'in', cap: 'Naí Dillí', f: 'Žije tu najviac ľudí na svete. Stojí tu nádherný Tádž Mahal.' },
      { n: 'Argentína', p: 'flag:ar', id: 'ar', cap: 'Buenos Aires', f: 'Krajina tanga a vysokých hôr Andy. Na vlajke má slnko.' },
      { n: 'Mexiko', p: 'flag:mx', id: 'mx', cap: 'Mexiko', f: 'Krajina starých pyramíd, kaktusov a veľkých klobúkov – sombrer.' },
      { n: 'Japonsko', p: 'flag:jp', id: 'jp', cap: 'Tokio', f: 'Ostrovná „krajina vychádzajúceho slnka“ – na vlajke má červené slnko.' },
      { n: 'Egypt', p: 'flag:eg', id: 'eg', cap: 'Káhira', f: 'Stoja tu slávne pyramídy a tečie tu rieka Níl.' },
      { n: 'Juhoafrická republika', p: 'flag:za', id: 'za', cap: 'Pretória', f: 'Krajina na juhu Afriky – žijú tu levy, slony aj tučniaky!' },
    ],
    quiz: [
      { q: 'Ktorá krajina je najväčšia na svete?', a: 'Rusko', o: ['Čína', 'USA', 'Brazília'] },
      { q: 'Ktorá krajina má na vlajke javorový list?', a: 'Kanada', o: ['USA', 'Austrália', 'Mexiko'] },
      { q: 'Koľko hviezd je na vlajke USA?', a: '50', o: ['12', '7', '100'] },
      { q: 'Kde stoja najslávnejšie pyramídy?', a: 'v Egypte', o: ['v Japonsku', 'v Kanade', 'v Rusku'] },
      { q: 'Ktorá vlajka je japonská?', pics: true, a: 'flag:jp', o: ['flag:kr', 'flag:cn', 'flag:ca'], f: 'Biela vlajka s červeným kruhom – slnkom.' },
      { q: 'Ktorá vlajka je kanadská?', pics: true, a: 'flag:ca', o: ['flag:us', 'flag:jp', 'flag:tr'] },
      { q: 'Ktorá vlajka je brazílska?', pics: true, a: 'flag:br', o: ['flag:ar', 'flag:in', 'flag:za'], f: 'Zelená so žltým kosoštvorcom a modrou nočnou oblohou.' },
      { q: 'V ktorej krajine žije najviac ľudí?', a: 'v Indii', o: ['na Slovensku', 'v Kanade', 'v Austrálii'] },
      { q: 'Kde je Veľký čínsky múr?', a: 'v Číne', o: ['v Mexiku', 'v Egypte', 'v Argentíne'] },
      { q: 'Aké je hlavné mesto Japonska?', a: 'Tokio', o: ['Peking', 'Moskva', 'Káhira'] },
    ],
    tf: [
      { s: 'Rusko je najväčšia krajina na svete.', ok: true },
      { s: 'Na vlajke Japonska je červený kruh.', ok: true },
      { s: 'Pyramídy stoja v Kanade.', ok: false, f: 'Najslávnejšie pyramídy stoja v Egypte.' },
      { s: 'Austrália je krajina aj svetadiel.', ok: true },
      { s: 'Na kanadskej vlajke je javorový list.', ok: true },
      { s: 'Brazília leží v Európe.', ok: false, f: 'Brazília je v Južnej Amerike.' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'find', rounds: 6, opts: 4, ask: 'Ktorá vlajka patrí krajine: {n}?' },
      { type: 'map', rounds: 8 },
      { type: 'mapname', rounds: 6, opts: 4 },
      { type: 'memory', pairs: 6 },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 6 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-places', title: 'Slávne miesta', sub: 'divy sveta', icon: '🗼', board: 'world',
    badge: { e: '🗼', name: 'Svetová turistka', desc: 'Vieš, kde sú slávne stavby sveta' },
    items: [
      { n: 'Eiffelova veža', p: 'foto:eiffelova-veza', id: 'fr', b: 'europe', flag: 'flag:fr', land: 'Francúzsko', f: 'Stojí v Paríži vo Francúzsku. Je vysoká 330 metrov – ako 100-poschodový dom!' },
      { n: 'Big Ben', p: 'foto:big-ben', id: 'gb', b: 'europe', flag: 'flag:gb', land: 'Veľká Británia', f: 'Slávna veža s hodinami v Londýne.' },
      { n: 'Koloseum', p: 'foto:koloseum', id: 'it', b: 'europe', flag: 'flag:it', land: 'Taliansko', f: 'Obrovská aréna v Ríme, stará takmer 2000 rokov.' },
      { n: 'Sagrada Família', p: 'foto:sagrada-familia', id: 'es', b: 'europe', flag: 'flag:es', land: 'Španielsko', f: 'Obrovský kostol v Barcelone. Stavajú ho už vyše 140 rokov!' },
      { n: 'Veterné mlyny', p: 'foto:veterne-mlyny', id: 'nl', b: 'europe', flag: 'flag:nl', land: 'Holandsko', f: 'Mlyny a polia tulipánov – to je Holandsko.' },
      { n: 'Socha slobody', p: 'foto:socha-slobody', id: 'us', b: 'world', flag: 'flag:us', land: 'USA', f: 'Stojí v New Yorku v USA. Bol to dar od Francúzska.' },
      { n: 'Veľký čínsky múr', p: 'foto:cinsky-mur', id: 'cn', b: 'world', flag: 'flag:cn', land: 'Čína', f: 'Najdlhšia stavba na svete – je dlhý tisíce kilometrov.' },
      { n: 'Tádž Mahal', p: 'foto:tadz-mahal', id: 'in', b: 'world', flag: 'flag:in', land: 'India', f: 'Nádherná biela mramorová stavba v Indii.' },
      { n: 'Opera v Sydney', p: 'foto:opera-sydney', id: 'au', b: 'world', flag: 'flag:au', land: 'Austrália', f: 'Budova v Austrálii, ktorá vyzerá ako lodné plachty.' },
      { n: 'Pyramídy', p: 'foto:pyramidy', id: 'eg', b: 'world', flag: 'flag:eg', land: 'Egypt', f: 'Obrovské kamenné hrobky egyptských kráľov – faraónov.' },
      { n: 'Hora Fudži', p: 'foto:fudzi', id: 'jp', b: 'world', flag: 'flag:jp', land: 'Japonsko', f: 'Najvyššia hora Japonska – sopka so snehovou čiapkou.' },
    ],
    quiz: [
      { q: 'V ktorom meste stojí Eiffelova veža?', a: 'v Paríži', o: ['v Ríme', 'v Londýne', 'v Madride'] },
      { q: 'Kto daroval USA Sochu slobody?', a: 'Francúzsko', o: ['Taliansko', 'Čína', 'Japonsko'] },
      { q: 'Kto dal postaviť pyramídy?', a: 'egyptskí králi – faraóni', o: ['rímski cisári', 'čínski draci', 'indiáni'] },
      { q: 'Ktorá stavba je najdlhšia na svete?', a: 'Veľký čínsky múr', o: ['Eiffelova veža', 'Koloseum', 'Big Ben'] },
      { q: 'V ktorom meste je Koloseum?', a: 'v Ríme', o: ['v Paríži', 'v Aténach', 'v Berlíne'] },
      { q: 'Čo je hora Fudži?', a: 'sopka v Japonsku', o: ['kostol v Španielsku', 'veža vo Francúzsku', 'múr v Číne'] },
      { q: 'Na čo sa podobá opera v Sydney?', a: 'na lodné plachty', o: ['na čižmu', 'na hrad', 'na pyramídu'] },
    ],
    tf: [
      { s: 'Eiffelova veža stojí v Londýne.', ok: false, f: 'Eiffelova veža stojí v Paríži. V Londýne je Big Ben.' },
      { s: 'Socha slobody stojí v New Yorku.', ok: true },
      { s: 'Pyramídy sú v Egypte.', ok: true },
      { s: 'Tádž Mahal je v Indii.', ok: true },
      { s: 'Koloseum je nová stavba z minulého roka.', ok: false, f: 'Koloseum je staré takmer 2000 rokov!' },
    ],
    acts: [
      { type: 'learn' },
      { type: 'match', pairs: 5, a: 'p', b: 'flag', title: 'Priraď vlajku krajiny' },
      { type: 'map', rounds: 5, board: 'europe', ask: 'Kde stojí {n}? Ťukni na krajinu.' },
      { type: 'map', rounds: 6, board: 'world', ask: 'Kde je {n}? Ťukni na krajinu.' },
      { type: 'quiz', rounds: 6 },
      { type: 'tf', rounds: 5 },
    ],
  },

  /* ------------------------------------------------------------------ */
  {
    id: 'geo-review', review: true, title: 'Veľká cesta', sub: 'opakovanie zemepisu', icon: '🏆',
    badge: { e: '🧳', name: 'Kráľovná cestovateliek', desc: 'Zvládla si celý zemepis!' },
    acts: [
      { type: 'bigquiz', rounds: 10 },
      { type: 'map', rounds: 8, board: 'europe', src: 'area' },
      { type: 'map', rounds: 8, board: 'world', src: 'area' },
      { type: 'memory', pairs: 6, src: 'area', flags: true },
      { type: 'mix', rounds: 8, src: 'area' },
    ],
  },
]);
